AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: orderapidynamodb

Globals:
  Function:
    Runtime: java21
    CodeUri: orderapidynamodb
    Architectures:
      - x86_64
    MemorySize: 512
    Timeout: 30
    Environment:
      Variables:
        ORDERS_TABLE: !Ref OrdersTable

Resources:
  OrdersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

  CreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.apis.CreateOrderLambda::createOrder
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
      Events:
        CreateOrderApi:
          Type: Api
          Properties:
            Path: /orders
            Method: POST

  RetrieveOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.apis.RetrieveOrderLambda::RetrieveOrder
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref OrdersTable
      Events:
        RetrieveOrderApi:
          Type: Api
          Properties:
            Path: /orders
            Method: GET
Outputs:
  OrdersApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/orders"
  CreateOrderFunctionArn:
    Description: "Create Order Lambda Function ARN"
    Value: !GetAtt CreateOrderFunction.Arn

  CreateOrderFunctionIamRoleArn:
    Description: "Create Order Lambda Function IAM Role ARN"
    Value: !GetAtt CreateOrderFunctionRole.Arn
