AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ordersapi

Resources:
  CreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ordersapi
      Handler: lambda.apis.CreateOrderLambda::createOrder
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512

      Events:
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: POST
  RetrieveOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ordersapi
      Handler: lambda.apis.RetrieveOrderLambda::RetrieveOrder
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512

      Events:
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: GET